### ISSUE TITLE
TypeError: val.indexOf is not a function

### ISSUE THREAD

**Issue by devurandom** [OpenLinkSoftware/OSDS_extension#4]
When I open https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv in my browser, OSDS takes over (it appears to be registered to handle this MIME type), but displays an error:
```
CSV discovered, but fails syntax checking by parser:
--
TypeError: val.indexOf is not a function
```

Browser console and debugger display no relevant information.

I am using OSDS 2.18.3 with Firefox 86 on Linux.

**Comment by smalinin** [comment]
Fixed in version >= 2.18.4 
New version will be uploaded soon.
