### ISSUE TITLE
.svg files not supported?

### ISSUE THREAD

**Issue by steltenpower** [OpenLinkSoftware/OSDS_extension#5]
I don't see .svg files mentioned somewhere.
(implement and) document ?
I'd love to help, though I don't know if I have the skills needed yet

**Comment by HughWilliams** [comment]
what are you seeking to be able to do, extract structured data from .svg files displayed in a browser page ?

**Comment by steltenpower** [comment]
Exactly that indeed

**Comment by smalinin** [comment]
.svg files are supported already in viewer.  OSDS supports .jpg .png .gif .svg files. 
And it supports also images in base64 format for jpg,png,gif, ie => `src="data:image/gif;base64,R0lGOD....`
https://github.com/OpenLinkSoftware/OSDS_extension/blob/669d9f5be85530378d5a32eac5ed0aefa0a125d5/src/html_gen.js#L351
